export const QUOTE_ACTION_TYPES = {
  SET_CURRENT_INDEX: "SET_CURRENT_INDEX",
  FETCH_QUOTES_START: "FETCH_QUOTES_START",
  FETCH_QUOTES_SUCCESS: "FETCH_QUOTES_SUCCESS",
  FETCH_QUOTES_FAILED: "FETCH_QUOTES_FAILED",
};
